### ISSUE TITLE
Unneeded reloading…

### ISSUE THREAD

**Issue by rmoriz** [chef-cookbooks/ohai#23]
https://github.com/opscode-cookbooks/ohai/blob/master/recipes/default.rb#L23-L26 is not included by default and forces reloads on every converge.

debug code:

```ruby
reload_ohai = false
# Add plugin_path from node attributes if missing, and ensure a reload of
# ohai in that case
unless Ohai::Config[:plugin_path].include?(node['ohai']['plugin_path'])

  Chef::Log.error("node path: #{node['ohai']['plugin_path']}")
  Chef::Log.error("config path: #{Ohai::Config[:plugin_path]}")

  Ohai::Config[:plugin_path] = [node['ohai']['plugin_path'], Ohai::Config[:plugin_path]].flatten.compact


  Chef::Log.error "reload_ohai 1: #{reload_ohai}"

  reload_ohai ||= true
end
Chef::Log.info("ohai plugins will be at: #{node['ohai']['plugin_path']}")
Chef::Log.error "reload_ohai 2: #{reload_ohai}"
```

output: 

```
      [2015-06-15T01:07:25+00:00] ERROR: node path: /etc/chef/ohai_plugins
       [2015-06-15T01:07:25+00:00] ERROR: config path: ["/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.3.0/lib/ohai/plugins"]
       [2015-06-15T01:07:25+00:00] ERROR: reload_ohai 1: false
       [2015-06-15T01:07:25+00:00] ERROR: reload_ohai 2: true
```

As seen with the `nginx` and `sysctl` cookbooks from supermarket.

related: https://github.com/miketheman/nginx/issues/344

- Chef 12.3.0-1, test-kitchen with vagrant & chef-zero 
- Ubuntu 12.04
- Ohai: 8.3.0

Example .kitchen.yml

```yaml
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
        - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[nginx::default]
```
